let mongoose = require("mongoose");
const Menproduct = require("./models/menProduct");



let products = [
  {
    name: "TGCW EAGLE HOODIE",
    img: "https://amiri.com/cdn/shop/products/1_AW23_MENS_JERSEY_TOP_TGCW_20EAGLE_20HOODIE_VINTAGE_20BLUE_EXTGMJL001-420_1.jpg?v=1695811872&width=1024",
    price: 122600.0,
    description: `
        AMIRI EXPANDS ITS UNIQUE CREATIVE PARTNERSHIP WITH LOS ANGELES-BASED UPCYCLING STUDIO, THE GREAT CHINA WALL. REIMAGINING FOUND GARMENTS SUCH AS MILITARY FATIGUES AND VINTAGE AMERICANA, REINTERPRETING THEM THROUGH INTRICATE EMBELLISHMENT AND HAND PAINTED GRAPHICS.

        AMIRI TGCW EXCLUSIVE CAPSULE

        MADE IN USA

        COTTON

        DRY CLEAN


        SKU: 191846547481


        FREE SHIPPING & RETURNS
        DUTIES & TAXES INCLUDED

        `,
  },

  {
    name: "TGCW CRYSTAL EAGLE HOODIE",
    img: "https://amiri.com/cdn/shop/products/2_AW23_MENS_JERSEY_TOP_TGCW_20CRYSTAL_20EAGLE_20HOODIE_VINTAGE_20BLACK_EXTGMJL002-097_1.jpg?v=1695809446&width=1024",
    price: 254800.0,
    description: `
     AMIRI EXPANDS ITS UNIQUE CREATIVE PARTNERSHIP WITH LOS ANGELES-BASED UPCYCLING STUDIO, THE GREAT CHINA WALL. REIMAGINING FOUND GARMENTS SUCH AS MILITARY FATIGUES AND VINTAGE AMERICANA, REINTERPRETING THEM THROUGH INTRICATE EMBELLISHMENT AND HAND PAINTED GRAPHICS.

AMIRI TGCW EXCLUSIVE CAPSULE

HAND-APPLIED CRYSTAL-STUDDING DETAILING

MADE IN USA

COTTON

DRY CLEAN


SKU: 191846547627


FREE SHIPPING & RETURNS
     
     `,
  },
  {
    name: "MA-1",
    img: "https://amiri.com/cdn/shop/products/156_AW23_Runway_SNEAKERS_SHOES_MA-1_AW23MFS009-111_WHITE_1_fab2f2d4-78c5-4c6b-8d6e-141fe6204303.jpg?v=1695810396&width=1024",
    price: 69700.0,
    description: `THE MA-1 IS AN ODE TO THE BOLD, AMPLIFIED SNEAKER SILHOUETTES OF '90S WEST COAST SKATE RENEGADES. CRAFTED ON AN EXAGGERATED RUBBER OUTSOLE, THIS SNEAKER CONTRASTS SUPPLE LEATHER WITH SOFT TOWELING ALONGSIDE PERFORATED PANELS, DOUBLE LACE FASTENING AND BRANDED EYELETS. THE MA ICON LENDS A SIGNATURE ELEMENT, WHILE THE QUILTED NUBUCK TONGUE IS SIGNED WITH MIKE AMIRI'S OWN WORDS: “ENGINEERED IN LOS ANGELES, CALIFORNIA. INSPIRED BY PRECIOUS MEMORIES. FOR THE YOUNG AND THE YOUNG AT HEART.”

     AUTUMN-WINTER 2023 COLLECTION
     
     100% LEATHER
     
     
     SKU: 191846521825
     
     
     FREE SHIPPING & RETURNS
     DUTIES & TAXES INCLUDED`,
  },

  {
    name: "WOLF LOGO TRUCKER HAT ",
    img: "https://amiri.com/cdn/shop/products/188_AW23_Runway_HATS_ACC_WOLF_20LOGO_20TRUCKER_20HAT_AW23MAH019-580_ACORN_1_9e8cb801-521e-4775-94ba-b0b542c74508.jpg?v=1695326006&width=1024",
    price: 28300.0,
    description: `AUTUMN-WINTER 2023 COLLECTION

     MADE IN USA
     
     100% COTTON
     
     
     SKU: 191846514094
     
     
     FREE SHIPPING & RETURNS`,
  },
];

async function seedDB() {
  await Menproduct.insertMany(products);
  console.log("db seeded");
}

module.exports = seedDB;
